### PR TITLE
New fork ; Updated tech summaries ; Corrected bibtex file

### PR DESCRIPTION
**Pull request by RituSanjay**

### CODE REVIEW

**Comment by laszewsk** [comment]
are you using an old fork?
please attend online hours

**Comment by laszewsk** [comment]
there is a conflict that i accepted anyways, but you need to fix

**Comment by RituSanjay** [comment]
Professor this is a new fork; do I create another new one?

**Comment by laszewsk** [comment]
i can not tell what you want to do as you closed this fork

**Comment by laszewsk** [comment]
i can not tell as you closed this request

**Pull request merged**
