### PR TITLE
fa18-523-68 Tech Summaries - Requested Fixes

### PR DESCRIPTION
**Pull request by seakkas**
Jclouds:
⭕️ start with a sentence what jClouds is
⭕️ use italics and not bold

-First paragraph removed.
-Bolds changed to italics.

OpenNebula: 
⭕️ grammar
⭕️ for consitency use italic do thi in your other contributions also

-Grammar checked.
-Bolds changed to italics.

Ceph:
⭕️ several paragraphs have no backing ref

-Requested references added.

e-Science Central:
- Main page reference added.

### CODE REVIEW

**Review by laszewsk — CHANGES_REQUESTED** [review]
Why are you changing the correct titles?

**Comment by sakkas20** [comment]
Old entries used for some references. Therefore, I deleted or edited some references.

**Review by laszewsk — APPROVED** [review]

**Comment by laszewsk** [comment]
you must not delete the old refernces, if you do not use them. they must stay in the list of refernces. please fix

**Comment by laszewsk** [comment]
e.g. they must stay in bitex, but you do not have to use them if they are irrelevant. however if they are relevant you may want to rethink your strategy or writeup

**Pull request closed without merging**
