### PR TITLE
Updated the Content for opennn.md Technology Abstract

### PR DESCRIPTION
**Pull request by arijitsinha80**
Hello Professor,

Thank you for your support and guidance, I have complete updates for my abstract.
Below is the list of abstracts updated. I have created individual pull request for the same.

1. opennn.md - Updated the content in the abstract.

Thanks,
Arijit Sinha
(hid-sp18-520)

### CODE REVIEW

**Comment by laszewsk** [comment]
can you improve the proper use of a and the

**Comment by arijitsinha80** [comment]
Hello Professor,

Thank you, I have updated the content, kindly let me know if you have any concerns.

Thanks,
Arijit Sinha

**Comment by laszewsk** [comment]
the contribution does not use proper plurals nor a and the correctly. I will accept anyways and try to correct.

**Comment by arijitsinha80** [comment]
Hello Professor,

Thank you for your support and guidance, I will work on the changes suggested and will provide another check in with updated content for Opennn.md.

I have 6 md files which I have worked on - recently I have submitted next updated file for Pytouch.md as new pull request. 

Thanks in Advance!!!

Thanks,
Arijit Sinha

**Pull request merged**
