### PR TITLE
Updated files

### PR DESCRIPTION
**Pull request by PrajaktaRPatil**

### CODE REVIEW

**Comment by PrajaktaRPatil** [comment]
I have updated my citations accordingly. Can you please accept my pull request.

**Comment by PrajaktaRPatil** [comment]
Hi Prof,

I have made changes to my tech summaries in the morning itself and added
citations before periods. If you think it is done correctly can you please
accept my pull request and add my tech summaries to cloudmesh.

Please let me know if I need to do anything else.

Thanks,
 Prajakta Patil.

**Comment by laszewsk** [comment]
you closed the pull request, so the changes were not applied. attend an online hour if unclear. Next one is Monday

**Comment by laszewsk** [comment]
you have a build error iin this one due to an old fork

**Comment by PrajaktaRPatil** [comment]
I will try to delete current fork and create new. If I am unable to do it ,
I will attend Monday meeting.

**Pull request closed without merging**
