### PR TITLE
went through all references regarding plasma-magma and edited them

### PR DESCRIPTION
**Pull request by IzoldaIU**
Per our discussion earlier today, I went through all plasma-magma references and removed the date and added month, doi, where they were missing

### CODE REVIEW

**Comment by IzoldaIU** [comment]
Professor, do I need to do anything else or am I good to go? I can close this pull requests if everything is ok.

**Comment by laszewsk** [comment]
THis is for you to decide and evaluate. I can not make that determination for you

**Comment by IzoldaIU** [comment]
I guess I am confused, as it didn't say that the pull request was accepted, just that you've merged the branch 'master' into master.

**Comment by IzoldaIU** [comment]
I think I am understanding what happened - you did the merge via command line, so the pull request didn't get automatically closed. It will get closed once you push the changes back to GitHub. Am I correct?

**Pull request merged**
