### PR TITLE
outdated: 523-53 bibtex File

### PR DESCRIPTION
**Pull request by ckakara**

### CODE REVIEW

**Comment by laszewsk** [comment]
outdated repository

**Comment by laszewsk** [comment]
you need to fix this today

**Comment by laszewsk** [comment]
You need to act upon this pull request as it is completly outdated and will never be accepted in thsi form. As the amount of changes you propose is small I recommend the following

a) go into your bib file via the GUI. Make the changes directly there. Make sure that you follow our FAQ we posted as a MIsc needs either a key or author field.

b) make sure you have no non-ASCII char in it 

c) you could paste the current content in the file on github into jabref and than add, and than coppy back 

d) than close this pull request.

**Comment by laszewsk** [comment]
only outstanding pull request by the way

**Comment by ckakara** [comment]
Hi Professor,

This was the pull request i initially created and circleCI failed for outdated repository.
Hence, i forked the project again to check in my changes as a new pull request.
The newly pull request is approved and merged. I could also see all my changes in master repository.
Here is the link for the new pull request.

https://github.com/cloudmesh/technologies/pull/485
I'm closing this now to avoid further confusion.

Thanks,
Chaitanya.

**Pull request closed without merging**
