### PR TITLE
submissions of 79

### PR DESCRIPTION
**Pull request by arapelli**

### CODE REVIEW

**Comment by arapelli** [comment]
Final submissions

**Comment by laszewsk** [comment]
there is no test performed here do you have an old fork? We do not accept pull requests that have not passed the tests

**Comment by laszewsk** [comment]
ok i fired off a test that for some reason was not done by you at time of checkin, so we do not yet know why this was the case, lets see what happens

**Comment by laszewsk** [comment]
ok, no test performed, indicating an old fork

**Pull request closed without merging**
