### PR TITLE
wrong quotes, conflicts: Update tajo.md

### PR DESCRIPTION
**Pull request by ebbeall**
Updated references.

### CODE REVIEW

**Comment by laszewsk** [comment]
can not merge due to conflicts. PLease redo

**Comment by ebbeall** [comment]
I do not understand why my latest commit is not passing the workflow check.  Could you please explain this?

**Comment by laszewsk** [comment]
you need to fix this today

**Comment by ebbeall** [comment]
Hi. I apologize. I do not understand what is failing the workflow check from my latest commit?

**Comment by ebbeall** [comment]
Makefile:66: recipe for target 'chars' failed
make: *** [chars] Error 1
Exited with code 2
That is the error I'm receiving and I do not understand how to fix it.

**Comment by laszewsk** [comment]
all errors are reported in circle ci, you can click on the red exclemation mark

then you will see https://circleci.com/gh/cloudmesh/technologies/519

this works for all errors

**Pull request merged**
