### PR TITLE
added the necessary changes to technology summaries

### PR DESCRIPTION
**Pull request by umabkota**

### CODE REVIEW

**Comment by laszewsk** [comment]
yoiu make this to complicated

**Comment by umabkota** [comment]
sorry for that, I'll create a new folder instead. Apologies.

**Comment by laszewsk** [comment]
what new folder?
the bib entries should sty where they are. mayeb i do not understand what you try to achieve. only thing you had to do is add the missing bibentries not move all the once you use in a separate file, only the once that you have created newly

**Comment by umabkota** [comment]
I had the missing bibtex also in the file but they were not showing up, so thought I'll remove them which are not showing up and create a new bib file with them

**Comment by laszewsk** [comment]
they will show up if you add the bibfile. you can look in the bib folder ...

**Comment by umabkota** [comment]
okay will do so, sorry for the confusion

**Pull request closed without merging**
