### PR TITLE
Update rabbitmq.md

### PR DESCRIPTION
**Pull request by yeyima**

### CODE REVIEW

**Comment by laszewsk** [comment]
you need to look in our improvement suggestions you just overwrite it and for example, do not integrate the missing references.

**Comment by laszewsk** [comment]
also you can not just constantly close our pull requests open a new one and then again ignore our suggestions ....

**Comment by laszewsk** [comment]
you can see all our suggestions if you look in your closed pull requests.

**Comment by yeyima** [comment]
it have the reference @fa18-523-74-Joern2009, also it's in the bibtex under bib file.

**Comment by laszewsk** [comment]
please come to zoom

**Comment by laszewsk** [comment]
i am there now

**Pull request merged**
