### PR TITLE
Update bittorrent.md

### PR DESCRIPTION
**Pull request by wangton**

### CODE REVIEW

**Comment by wangton** [comment]
I added another Paragraphs describe that BT do not need one super high bandwidth by break the file to small piece and every client can be a server.

**Comment by wangton** [comment]
I added another Paragraphs describe that BT do not need one super high bandwidth by break the file to small piece and every client can be a server. 
I added those part 6hours ago, why it still not prove the request? It’s that you do not read it yet or I still need to do some editing? If I still need to do some editing, there is no comment after I finish adding this part.

**Comment by laszewsk** [comment]
we will discuss this submission in more detail next week with the graders. I is not counted as late submission. We just need to make sure we review it regarding the comments already previously posted.

**Comment by wangton** [comment]
I revision it based on your comments, “It’s not only for faster download speed” so I add an other part talk about the bandwidth. 
Another comment “ something is not related to Bittorrent” I deleted those things. 
For another comment “not personal opinion” so I change it also.
For the last comment “ref missing” I add the original reference which can download Bittorrent already in the previous bin text.

I had finish all those things, why still can not prove the pull request? What else should I edit?

**Comment by laszewsk** [comment]
because we need more time for the review

**Pull request merged**
