### PR TITLE
Update globus-online-gridftp.md

### PR DESCRIPTION
**Pull request by yeyima**

### CODE REVIEW

**Comment by yeyima** [comment]
you do not even give any comments on that page.

**Comment by laszewsk** [comment]
come on zoom you make it too cpmplicated

**Comment by laszewsk** [comment]
i am in zoom waiting

**Comment by yeyima** [comment]
it's to late, I don't want to bother you. I can ask TA tomorrow

**Comment by yeyima** [comment]
thank you for give me feedback at this late, I don't want to bother you at this late time.

**Comment by laszewsk** [comment]
i am glad to help

**Comment by laszewsk** [comment]
zoom meeting clarified that the required change takes 30 seconds

**Pull request merged**
